fix: tmux sessionizer breaks when folder does not exist
Sessionizer fails when a folder passed to find doesn not exist. Find
then returns a NZEC which due to my bash defaults exits the progrom.
This means that I never run the code that switches or creates the new
session. This patch also supresses any errors find writes to stderr when
a folder doens't exist. We just don't care about these errors and they
are noisy.

The reason for this change is that it is technically possible to pass a
non existing folder to -w. But also my defaults are ~/Projects and
~/Work. I don't have a work folder on my personal computer. I rather
have find silently fail and show a list of empty folders. This is what
did already and indicates to the user that something went wrong.

diff --git a/.local/bin/tmux-sessionizer b/.local/bin/tmux-sessionizer
--- a/.local/bin/tmux-sessionizer
+++ b/.local/bin/tmux-sessionizer
@@ -1,12 +1,10 @@
 #!/usr/bin/env bash
 
-# Stop script on NZEC
-set -e
-# Stop script if unbound variable found (use ${var:-} if intentional)
-set -u
-# By default cmd1 | cmd2 returns exit code of cmd2 regardless of cmd1 success
-# This is causing it to fail
-set -o pipefail
+# -e Stop script on None Zero Exit Code (NZEC)
+# -u Stop script if unbound variable found (use ${var:-} if intentional)
+# -o By default cmd1 | cmd2 returns exit code of cmd2 regardless of cmd1 success
+set -euo pipefail
+IFS=$'\n\t'
 
 usage() {
   echo "Usage: tmux-sessionizer [OPTION]
@@ -20,7 +18,9 @@ tmux-sessionizer() {
     tmux="${TMUX:-}"
 
     if [[ -z "$selected" ]]; then
-        selected=$(find ~/Projects ~/Work -mindepth 1 -maxdepth 1 -type d | fzf)
+        set +e # Disable failing on NZEC, if a directory doesn't exist find returns a NZEC. We just don't care about it.
+        selected=$(find ~/Projects ~/Work -mindepth 1 -maxdepth 1 -type d 2> /dev/null | fzf)
+        set -e
     fi
 
     if [[ -z $selected ]]; then
